name: Build and Push

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: sudo apt-get install -y build-essential

    - name: Run build script
      run: |
        mkdir -p out
        chmod +x build.sh 
        ./build.sh -m z3s -k n -c y
        mv build/* out/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: out
